### ISSUE TITLE
Uzina Getica backpack - unable to select talent

### ISSUE THREAD

**Issue by wkrick** [mxswat/mx-division-builds#73] opened 2022-12-07 19:07 UTC
Screenshot:  
![image](https://user-images.githubusercontent.com/10203734/206273108-666ae48e-9866-4c22-9cfd-97cf01e76ba9.png)

Link to build:  
https://mxswat.github.io/mx-division-builds/#/MwFgtAjAbGMEyzABmalSBcICciEJnTWQwFYI8wCxhDjMJcZgr76MmbWieSRqWCXjwxwQADlTZcEUjKgVoKaELQYI48OHEtSVOsIzC2IuEA

**Comment by Kiochyy** [comment] 2023-02-02 21:29
Hi,

The builder was updated late december or so with a fix for the uzina backpack talent. I see your link working on my end, check it again, it should be good.

Closing it as solved, please reopen or submit a bug report in the discord it if the issue is not solved on your end

Thanks for the report

**Closed by Kiochyy** 2023-02-02 21:29 UTC
